language: objective-c 
cache: cocoapods
osx_image: xcode8

before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - gem install cocoapods
    - gem install xcpretty
    - travis_wait 20 pod repo update --silent

install: travis_wait 30 pod install

xcode_workspace: Pickery.xcworkspace
xcode_scheme: iOS
xcode_sdk: iphonesimulator8.4
