language: objective-c 
cache: cocoapods
osx_image: xcode8.2

# before_install:
#     - brew update
#     - brew outdated xctool || brew upgrade xctool
#     - gem install cocoapods
#     - gem install xcpretty
#     - pod repo update --silent

# install: pod install
xcode_workspace: Pickery.xcworkspace
xcode_scheme: iOS
xcode_sdk: iphonesimulator8.4
